[package]
name = "project_helper"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = {version = "0.4.39", features = ["serde"]}
serde ={ version = "*", features = ["derive"] }
serde_json = "*"
home = "0.5.*"
